Use the same metric for overall and validation
ImageMarkup/isic-challenge-scoring pull request #114
Opened 2020-12-11 07:38 UTC by danlamanna

@brianhelba Note the `TODO` comments. You said the overall was already computed I just needed to find it?

2020-12-11 17:39 UTC, brianhelba requested changes
Some inline comments, and fixes for getting the overall metrics.

I'd like to put the default for the target metric at the CLI level only, as a quality of life convenience for end users. I'm worried that if we have it the internal API, we may forget to include it, resulting in bugs.

Additionally, you can remove the `Optional`-ness of the `Score.validation` property, from the parent dataclass.

2020-12-11 17:39 UTC, brianhelba commented on isic_challenge_scoring/classification.py
> +            self.overall = self.aggregate.at['balanced_accuracy']  # TODO
```suggestion
            self.overall = self.macro_average['ap']
```

2020-12-11 17:39 UTC, brianhelba commented on isic_challenge_scoring/classification.py
> +            self.overall = self.aggregate.at['balanced_accuracy']  # TODO
```suggestion
            self.overall = self.macro_average['auc']
```

2020-12-11 17:39 UTC, brianhelba commented on isic_challenge_scoring/classification.py
> +        target_metric: ValidationMetric = ValidationMetric.BALANCED_ACCURACY,
```suggestion
        target_metric: ValidationMetric,
```

I'm fine if the internal API makes this mandatory. A default might be a source of bugs.

2020-12-11 17:39 UTC, brianhelba commented on isic_challenge_scoring/classification.py
> +        target_metric: ValidationMetric = ValidationMetric.BALANCED_ACCURACY,
```suggestion
        target_metric: ValidationMetric,
```

2020-12-11 17:39 UTC, brianhelba commented on isic_challenge_scoring/classification.py
> +        target_metric: ValidationMetric = ValidationMetric.BALANCED_ACCURACY,
```suggestion
        target_metric: ValidationMetric,
```

2020-12-11 17:39 UTC, brianhelba commented on tests/test_classification.py
> +        target_metric=target_metric,
```suggestion
        target_metric,
```

2020-12-11 17:39 UTC, brianhelba commented on tests/test_classification.py
>  @pytest.mark.parametrize(
You can remove the plain `test_score` test above.

2020-12-11 17:39 UTC, brianhelba commented on tests/test_classification.py
> +def test_score_target_metric(
```suggestion
def test_score(
```

Since `target_metric` can be mandatory, this test case is semantically more general.

2020-12-11 17:39 UTC, brianhelba commented on isic_challenge_scoring/classification.py
> +        target_metric: ValidationMetric = ValidationMetric.BALANCED_ACCURACY,
Rename the `ValidationMetric` enum to `TargetMetric`?

2020-12-11 17:50 UTC, brianhelba commented on isic_challenge_scoring/classification.py
> +        target_metric: ValidationMetric = ValidationMetric.BALANCED_ACCURACY,
Actually, how about `ClassificationTargetMetric` or `ClassificationMetric`? I think we'll want a similar one for segmentation in the future.

2020-12-20 05:12 UTC, danlamanna commented
@brianhelba The typechecking will fail until the #115 is merged.

2020-12-20 05:13 UTC, danlamanna commented
The corresponding change to stade still needs to happen.

2020-12-20 18:32 UTC, brianhelba approved these changes

2020-12-23 05:56 UTC, merged