Misc fixes
ImageMarkup/isic-challenge-scoring pull request #43
Opened 2019-03-11 18:48 UTC by danlamanna

2019-03-12 20:13 UTC, brianhelba commented on tox.ini
> +basepython = 37
`basepython ` here is illegal: https://tox.readthedocs.io/en/latest/config.html

2019-03-12 20:14 UTC, brianhelba commented on tox.ini
>  [testenv:flake8]
If you want to call this `lint`, go for it.

2019-03-12 20:28 UTC, brianhelba commented on tox.ini
> +[testenv:py37]
Change to `[testenv]`

2019-03-12 20:29 UTC, brianhelba requested changes
See

2019-03-12 23:51 UTC, danlamanna commented
I fixed thisk

2019-03-12 23:53 UTC, danlamanna commented
I fixed this up a bit, but this definitely does not work on a clean checkout. All the tests fail because of the data files not being checked out. I tried adding a commands_pre in the tox setup, but it's very difficult to test because git lfs caches the objects and makes it hard to clean everything out.

2019-03-27 17:58 UTC, brianhelba approved these changes

2019-03-27 17:58 UTC, merged